# Generated by Django 3.2.6 on 2022-04-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220322_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Business',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Entertainment',
            new_name='entertainment',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='General',
            new_name='general',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Health',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Science',
            new_name='science',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Sports',
            new_name='sports',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Technology',
            new_name='technology',
        ),
    ]
