# Generated by Django 3.2.6 on 2022-04-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220420_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='business',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='entertainment',
            new_name='Entertainment',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='general',
            new_name='General',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='health',
            new_name='Health',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='science',
            new_name='Science',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='sports',
            new_name='Sports',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='technology',
            new_name='Technology',
        ),
    ]
